### ISSUE TITLE
Error loading certificate: x509: failed to parse ECDSA parameters as named curve

### ISSUE THREAD

**Issue by xamroot** [ns1/doq-proxy#1]
I ran into this issue after attempting to run sudo ./proxy following key generation. This issue was encountered on CentOS 7. The full error message was: msg="terminating after error" err="load certificate: x509: failed to parse ECDSA parameters as named curve. The two commands I ran to generate the key were as follows `open ssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -out key.pem` and `openssl req -x509 -days 365 -subj "\CN-DNS-over-QUIC Test" -key key.pem -out cert.pem`. I was unable to use the option -addext as I would get an error stating that the option is non existent, I do not think it is related to the issue. I have found a fix for anyone who may encounter a similar error. Replace the first key generation command with `open ssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -pkeyopt ec_param_enc:named_curve -out key.pem` and doq proxy should run correctly. If the creators see this they should mark the issue as closed, I wanted to post this to save anyone who may run into the error some googling time.

**Comment by wwb203** [comment]
I ran into the same issue. Thank you so much for the tip.

**Comment by xamroot** [comment]
@wwb203 Glad I was able to help!

**Comment by fcelda** [comment]
Thank you, @xamroot. This completely slipped my radar.

OpenSSL on CentOS 7 seems to use explicit curve encoding (`ec_param_enc:explicit`) by default while Go seems to support only named curves (`ec_param_enc:named_curve`).

I've updated the README to always include the later option.
